language: go

sudo: false

matrix:
  include:
  - go: "1.9.x"
  - go: "1.10.x"
  - go: "1.11.x"
    env:
      - GO111MODULE=off
  - go: "1.11.x"
      - GO111MODULE=on

install: make deps

script: make ci-test

matrix:
  allow_failures:
    - go: 'tip'

