[[constraint]]
  name = "github.com/gobuffalo/envy"
  version = "1.6.3"

[[constraint]]
  branch = "master"
  name = "github.com/gobuffalo/genny"

[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "1.11.1"

[[constraint]]
  name = "github.com/gobuffalo/plush"
  version = "3.7.7"

[[constraint]]
  name = "github.com/markbates/going"
  version = "1.0.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[prune]
  go-tests = true
  unused-packages = true
